[tool.black]
line-length = 140
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)

'''
